# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  server_host: 0.0.0.0
  #server_host: 100.95.132.49

logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug

homekit:
  - filter:
      include_domains:
        - light
      include_entity_globs:
        - sensor.*_humidity
        - sensor.*_temperature
        - media_player.lg_webos_tv_oled55c2psa
    port: 21064
    #ip_address: 100.95.132.49
    ip_address: 0.0.0.0
    advertise_ip:
      - 100.95.132.49
